# Generated by Django 2.0.7 on 2019-12-20 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jottings',
        ),
        migrations.AddField(
            model_name='articles',
            name='belong_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.Info'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='info',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='is_index',
            field=models.BooleanField(default=0, verbose_name='是否首页轮播'),
        ),
    ]
